# Generated by Django 3.1.7 on 2021-03-02 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_auto_20210302_0721'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sweetness', models.FloatField()),
                ('saltiness', models.FloatField()),
                ('sourness', models.FloatField()),
                ('bitterness', models.FloatField()),
                ('savoriness', models.FloatField()),
                ('fattiness', models.FloatField()),
                ('spiciness', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
